# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
        exclude: 'deploy/piraeus/'
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: 'charts/'
        args:
          - --multi
      - id: check-added-large-files
  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: master
    hooks:
      - id: gofumpt
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: golangci-lint
        args:
          - --new-from-rev=HEAD
      - id: go-unit-tests
  - repo: local
    hooks:
      - id: generate-deep-copy
        name: generated deep-copy code must be up-to-date
        language: system
        files: '^pkg/apis/.*\.go$'
        pass_filenames: false
        entry: make deep-copy
      - id: generate-crds
        name: generated crds must be up-to-date
        language: system
        files: '^pkg/apis/.*\.go$'
        pass_filenames: false
        entry: make crds
      - id: generate-cn-values
        name: generate helm values for CN users
        language: system
        files: '^charts/piraeus/values.*\.yaml'
        pass_filenames: false
        entry: make helm-values
      - id: generate-piraeus-yaml
        name: generate full yaml deployment from helm templates
        language: system
        files: '(^charts/piraeus/.*)|(^deploy/piraeus/.*)'
        pass_filenames: false
        entry: make deploy/piraeus
