# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: charts/.*/templates/.*
        args:
          - --multi
      - id: check-added-large-files
  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.2
    hooks:
      - id: gofumpt
      - id: golangci-lint
        args:
          - --new-from-rev=HEAD
  - repo: local
    hooks:
      - id: generate-deep-copy
        name: generated deep-copy code must be up-to-date
        language: system
        pass_filenames: false
        entry: make manifests
      - id: run-tests
        name: Run go tests
        language: system
        pass_filenames: false
        entry: make test
