apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-chowner
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "post-install-labels" . | indent 4 }}
  annotations:
    "helm.sh/hook-weight": "-5"
{{ include "post-install-annotations" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-chowner
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "post-install-labels" . | indent 4 }}
  annotations:
    "helm.sh/hook-weight": "-5"
{{ include "post-install-annotations" . | indent 4 }}
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - privileged
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-chowner
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "post-install-labels" . | indent 4 }}
  annotations:
    "helm.sh/hook-weight": "-5"
{{ include "post-install-annotations" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-chowner
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-chowner
---
{{- if .Values.pspRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-psp
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "post-install-labels" . | indent 4 }}
  annotations:
    "helm.sh/hook-weight": "-5"
{{ include "post-install-annotations" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.pspRole }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-chowner
{{- end }}
---
{{ range (required "A valid .Values.nodes entry required!" .Values.nodes) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Release.Name }}-{{ . }}
  namespace: {{ $.Release.Namespace | default "default" }}
spec:
  capacity:
    storage: {{ required "A valid .Values.size entry required!" $.Values.size }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: {{ required "A valid .Values.path entry required!" $.Values.path }}
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ . }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Release.Name }}-{{ . }}-chown
  namespace: {{ $.Release.Namespace | default "default" }}
  labels:
{{ include "post-install-labels" $ | indent 4 }}
  annotations:
{{ include "post-install-annotations" $ | indent 4 }}
spec:
  template:
    metadata:
      name: {{ $.Release.Name }}-{{ . }}-chown
      namespace: {{ $.Release.Namespace | default "default" }}
    spec:
      serviceAccountName: {{ $.Release.Name }}-chowner
      restartPolicy: Never
      containers:
        - name: chown
          securityContext:
            privileged: true
          image: {{ $.Values.chownerImage | quote }}
          command:
            - sh
            - -ce
            - |
              chown -R {{ $.Values.uid | default 1000 }}:{{ $.Values.uid | default 1000 }} /volume
              chmod -R 0775 /volume
              {{- if $.Values.selinux }}
              chcon -R -t container_file_t /volume
              {{- end }}
          volumeMounts:
            - mountPath: /volume
              name: pv
      volumes:
        - name: pv
          hostPath:
            type: DirectoryOrCreate
            path: {{ required "A valid .Values.path entry required!" $.Values.path }}
      tolerations:
{{ $.Values.tolerations | toYaml | indent 8 }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - {{ . }}
---
{{ end }}
