apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: piraeuscontrollersets.piraeus.linbit.com
spec:
  group: piraeus.linbit.com
  names:
    kind: PiraeusControllerSet
    listKind: PiraeusControllerSetList
    plural: piraeuscontrollersets
    singular: piraeuscontrollerset
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: PiraeusControllerSet is the Schema for the piraeuscontrollersets
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: PiraeusControllerSetSpec defines the desired state of PiraeusControllerSet
          properties:
            etcdURL:
              type: string
            drbdRepoCred:
              description: DrbdRepoCred is the name of the kubernetes secret that
                holds the credential for the DRBD repositories
              type: string
          required:
          - etcdURL
          - drbdRepoCred
          type: object
        status:
          description: PiraeusControllerSetStatus defines the observed state of PiraeusControllerSet
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
