# This YAML file contains all RBAC objects that are necessary to run a
# LINSTOR controller pod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: linstor-controller
  namespace: {{ .Release.Namespace }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linstor-leader-elector
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["create", "patch", "update"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linstor-leader-elector
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: linstor-leader-elector
subjects:
  - kind: ServiceAccount
    name: linstor-controller
