{{- if and .Values.operator.controller.enabled (not .Values.operator.controller.luksSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "operator.fullname" . }}-passphrase
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
immutable: true
data:
  {{- /* We have to be careful not to override the original secret value, otherwise encrypted data could be lost forever */}}
  {{- $secret := lookup "v1" "Secret" .Release.Namespace (printf "%s-passphrase" ( include "operator.fullname" . )) }}
  {{- if $secret }}
  MASTER_PASSPHRASE: {{ $secret.data.MASTER_PASSPHRASE | quote }}
  {{- else }}
  MASTER_PASSPHRASE: {{ .Values.operator.controller.masterPassphrase | default (randAlphaNum 40) | b64enc | quote }}
  {{- end }}
{{- end }}
