kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "piraeus-operator.fullname" . }}-csi-driver-registrar-binding
subjects:
  - kind: ServiceAccount
    name: {{ template "piraeus-operator.fullname" . }}-csi-node-sa
    # You must change this to the current context
    namespace: default
roleRef:
  kind: ClusterRole
  name: {{ template "piraeus-operator.fullname" . }}-csi-driver-registrar-role
  apiGroup: rbac.authorization.k8s.io
