apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "piraeus-operator.fullname" . }}-operator
  labels:
    name: {{ template "piraeus-operator.fullname" . }}-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ template "piraeus-operator.fullname" . }}-operator
  template:
    metadata:
      labels:
        name: {{ template "piraeus-operator.fullname" . }}-operator
    spec:
      serviceAccountName: {{ template "piraeus-operator.fullname" . }}-operator
      containers:
        - name: piraeus-operator
          image: {{ .Values.operator.image.repo }}/{{ .Values.operator.image.name }}:{{ .Values.operator.image.version }}
          command:
          - piraeus-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "piraeus-operator"
      imagePullSecrets:
      - name: {{ .Values.drbdRepoCred }}
