---
# Source: piraeus/charts/etcd/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: piraeus-op-etcd
  namespace: default
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    heritage: "Helm"
    release: "piraeus-op"
    chart: "etcd-0.7.4"
    app: etcd
spec:
  ports:
  - port: 2380
    name: etcd-server
  - port: 2379
    name: etcd-client
  clusterIP: None
  selector:
    app: etcd
    release: "piraeus-op"
