---
# Source: piraeus/templates/operator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piraeus-op-operator
  namespace: default
  labels:
    name: piraeus-op-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: piraeus-op-operator
  template:
    metadata:
      labels:
        name: piraeus-op-operator
    spec:
      serviceAccountName: piraeus-op
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: piraeus-operator
          image: quay.io/piraeusdatastore/piraeus-operator:v1.6.0
          imagePullPolicy: "IfNotPresent"
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "piraeus-operator"
          resources:
            {}
      tolerations: []
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  name: piraeus-op-operator
