---
# Source: piraeus/templates/operator-satelliteset.yaml
apiVersion: piraeus.linbit.com/v1
kind: LinstorSatelliteSet
metadata:
  name: piraeus-op-ns
  namespace: default
  labels:
    name: piraeus-op-ns
spec:
  priorityClassName: ""
  sslSecret: ""
  drbdRepoCred: ""
  imagePullPolicy: "IfNotPresent"
  satelliteImage: quay.io/piraeusdatastore/piraeus-server:v1.20.0-rc.1
  linstorHttpsClientSecret: ""
  controllerEndpoint: http://piraeus-op-cs.default.svc:3370
  automaticStorageType: "None"
  affinity: {}
  tolerations: []
  resources: {}
  monitoringImage: "quay.io/piraeusdatastore/drbd-reactor:v0.8.0"
  kernelModuleInjectionMode: "Compile"
  kernelModuleInjectionImage: "quay.io/piraeusdatastore/drbd9-bionic:v9.1.11"
  kernelModuleInjectionResources: {}
